### ISSUE TITLE
Enforce code review

### ISSUE THREAD

**Issue by creideiki** [saab-simc-admin/workflow-tools#11]
GitHub lets us enforce code review before a branch can be merged: https://help.github.com/articles/enabling-required-reviews-for-pull-requests/

Since that matches what we are already doing, we should enable that functionality in all @saab-simc-admin repos.

I'm not sure how that interacts with our manual merge workflow, but if someone with admin privileges turns it on I can check if `git-ghpr` could be updated to take it into account.

**Comment by notCalle** [comment]
Review is now enforced for [workflow-tools](/saab-simc-admin/workflow-tools), so we'll see how that interacts with #10.

**Comment by notCalle** [comment]
Success! Without an accepting review this happens:
```
remote: Resolving deltas: 100% (19/19), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least one approved review is required by reviewers with write access.
```
